### PR TITLE
Add arb_mat_eq/ne (and more)!

### PR DESCRIPTION
**Pull request by thofma**
If the functions look fine to you, I can add documentation.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Look good. Documentation would be nice! You might also copy+replace to add the corresponding functions for acb_mat.

**Comment by thofma** [comment]
If you are ok with the wording, I will add the corresponding acb_mat functions.

**Comment by fredrik-johansson** [comment]
The wording seems ok.

**Comment by fredrik-johansson** [comment]
You added declarations for set/set_round_arb_mat methods. Do you intend to add these functions in this PR?

**Comment by thofma** [comment]
This was actually not intended. But now as it is open and the signatures added, I may as well add these functions here.

**Pull request merged**
