### PR TITLE
platt whittaker shannon interpolation

### PR DESCRIPTION
**Pull request by p15-git-acc**
This PR implements the Whittaker-Shannon interpolation component of Platt's method of isolating zeta zeros. Here's an example plot of the interpolation (with error bounds):
interpolation plot

### CODE REVIEW

**Comment by p15-git-acc** [comment]
I think all of the issues flagged by 'codacy' are false positives.

**Comment by fredrik-johansson** [comment]
> I think all of the issues flagged by 'codacy' are false positives.

Yes, it looks OK to me.

**Comment by fredrik-johansson** [comment]
Apologies for the delay -- the code looks great.

**Comment by p15-git-acc** [comment]
My progress on implementing the platt zeta zeros algorithm (in particular selecting tuning parameter values automatically) got hung up on unexpectedly inefficient incomplete gamma function evaluation. I found https://arxiv.org/abs/1803.07841 using google, which looked promising for the transition region where the trouble appeared to be, but I don't know if it's suitable for implementing in arb.

**Comment by fredrik-johansson** [comment]
Inefficient or inaccurate? It doesn't seem like it should be the bottleneck in the algorithm.

If it's just used for estimates and doesn't require bounds, that would make things easier.

**Comment by p15-git-acc** [comment]
> Inefficient or inaccurate?

Imprecise but becomes inefficient when working around the imprecision.

> It doesn't seem like it should be the bottleneck in the algorithm.

For most parameter combinations it's not the bottleneck in the algorithm in this pull request (which itself will probably not be the bottleneck in the platt zeta zeros algorithm), but it's the bottleneck in a script that I tried to use to help develop tuning parameter heuristics.

**Pull request merged**
