### PR TITLE
CMake build

### PR DESCRIPTION
**Pull request by isuruf**
CMake can generate Visual Studio projects. I tried this out to build a static library of Arb in Windows using MSVC and it works great. Test failures are given at the end.

Shared library fails because of a bug in Flint. I get lots of unresolved symbols issues (eg. `_fmpz_new_mpz` is not found)

Let me know if you are interested in a CMake build.

Failures
630 - partitions-t-partitions_fmpz_ui_threaded (OTHER_FAULT)

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Seems ok, though I would prefer to avoid maintaining parallel build systems if possible. The failures look rather serious. If the goal is to support MSVC then it would best to fix them...

**Comment by isuruf** [comment]
Goal was to support MSVC. It's hard to generate visual studio projects by scripts like in flint. CMake makes it easier.
I'll have a look to see why the tests are failing. Flint also has a few tests failing on MSVC. Maybe they have an impact.

**Comment by fredrik-johansson** [comment]
It makes sense to fix all test failures in Flint first.

**Comment by isuruf** [comment]
All, but one test passes. 

Failing test case is  [partitions-t-partitions_fmpz_ui_threaded](https://github.com/fredrik-johansson/arb/blob/05f7dbd729d6b661e82f6dae4200f94289efc37b/partitions/test/t-partitions_fmpz_ui_threaded.c)

It fails with the following message,
```
partitions_fmpz_ui_threaded....Exception (FLINT memory_manager). Unable to allocate memory (736)
```
Have you got any idea how to solve this?

**Comment by fredrik-johansson** [comment]
If it's failing to allocate memory, it probably means a junk value is being computed somewhere, which one should be able to track down... I don't know anything about debugging on Windows though.

**Comment by isuruf** [comment]
Fixed the error. See the last commit message.
Now all tests pass with MSVC.

**Comment by fredrik-johansson** [comment]
Excellent. Thanks for the fix. One more concern: would it be possible to autogenerate the module list (it's currently out of date...)?

**Comment by isuruf** [comment]
Hmm, do you have an idea of how to do that without considering .git folder and build folders? Maybe checking the header files in the root folder would work right?

**Comment by fredrik-johansson** [comment]
I don't know what would be the easiest way to code it with CMake, but checking the header files should work.

**Comment by isuruf** [comment]
Now the module list is autogenerated.

**Comment by fredrik-johansson** [comment]
Perfect. Could you also add a short section to the documentation (setup.rst) about how to use the CMake build?

**Comment by fredrik-johansson** [comment]
Thanks!

**Pull request merged**
