### PR TITLE
ENH: better entrywise truncation errors for matrix powers

### PR DESCRIPTION
**Pull request by argriffing**
Improves entrywise error bounds for the matrix exponential. This method detects all entries for which a matrix Taylor series can be safely truncated to N terms given the sparsity structure of the matrix.
```
exp(
[1, 1, 0, 0]
[0, 0, 1, -1]
[0, 0, 0, 2]
[0, 0, 0, 0]
)

before PR:
[2.71828182786703 +/- 9.315e-10, 1.71828182833269 +/- 4.6574e-10,
0.718281828332692 +/- 2.3286e-10, -0.281718171434477 +/- 1.1644e-10]
[0 +/- 0, 1 +/- 0, 1 +/- 9.3326e-17, 0 +/- 2.2457e-16]
[0 +/- 0, 0 +/- 0, 1 +/- 0, 2 +/- 9.3326e-17]
[0 +/- 0, 0 +/- 0, 0 +/- 0, 1 +/- 0]

after PR:
[2.71828182786703 +/- 9.315e-10, 1.71828182833269 +/- 4.6574e-10,
0.718281828332692 +/- 2.3285e-10, -0.281718171434477 +/- 1.1644e-10]
[0 +/- 0, 1 +/- 0, 1 +/- 0, 0 +/- 0]
[0 +/- 0, 0 +/- 0, 1 +/- 0, 2 +/- 0]
[0 +/- 0, 0 +/- 0, 0 +/- 0, 1 +/- 0]
```

Note that this method does not detect safe truncation when the safety depends on the signs of the matrix entries.
```
exp(
[5, -3, 2]
[15, -9, 6]
[10, -6, 4]
)

[6 +/- 6.0699e-12, -3 +/- 1.7207e-12, 2 +/- 2.689e-12]
[15 +/- 7.9052e-12, -8 +/- 4.4027e-12, 6 +/- 3.7133e-12]
[10 +/- 1.1039e-11, -6 +/- 3.3604e-12, 5 +/- 4.9288e-12]
```

### CODE REVIEW

**Comment by argriffing** [comment]
This uses the last of the new `bool_mat` functions.

**Comment by fredrik-johansson** [comment]
Looks good.

**Comment by fredrik-johansson** [comment]
In fact Pascal matrices are computed exactly now, which is quite nice: https://en.wikipedia.org/wiki/Pascal_matrix

**Comment by argriffing** [comment]
> In fact Pascal matrices are computed exactly now, which is quite nice

Cool, I guess the exactness is not only due to recognizing that the series is finite; it also must avoid intermediate calculations like (1/3)*6.

**Comment by fredrik-johansson** [comment]
Correct, it's because there's only a single final division.

**Pull request merged**
