### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by isuruf**
OS X test with gcc timeouts.

@fredrik-johansson, you mentioned in symengine/symengine#877 that the tests could be reduced with something like `flint_test_multiplier()`. How do I do that?

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
I just added such a mechanism. It works slightly differently than flint: it's controlled by an environment variable, and it's a float with the default value 1.0. So `export ARB_TEST_MULTIPLIER=0.1` should do the trick.

By the way, I do think we should test against the latest released version of flint rather than the latest git version, since it's important that this works (and the git version is what I always test against anyway). Which means a quick workaround for the discrete log failure is required.

**Comment by isuruf** [comment]
Builds now pass on Linux and OS X

**Comment by fredrik-johansson** [comment]
Thanks!

**Comment by fredrik-johansson** [comment]
I'm looking at the build log now and it's rebuilding the dependencies from scratch. Is there a reason why they have not been cached?

**Comment by isuruf** [comment]
I didn't add any caching, because caching for OS X is only for travis pro customers.

**Comment by fredrik-johansson** [comment]
What about Linux?

**Comment by isuruf** [comment]
Caching in Linux can be done, although the total test time will depend on the slowest test which is the OSX gcc test.

**Comment by fredrik-johansson** [comment]
Sure, but it's nice to save server resources, and it's useful to see the results of the first test as soon as possible (for which reason ARB_TEST_MULTIPLIER could be set to a smaller value even on Linux).

**Comment by isuruf** [comment]
Sounds reasonable. I'll send a PR soon

**Comment by fredrik-johansson** [comment]
There's something wrong with the mac gcc build. It builds dependencies up until configuring flint, but then it just stalls without doing anything.

**Comment by fredrik-johansson** [comment]
Oh wait, I think I see why. The output when building FLINT is piped to /dev/null. If FLINT takes more than 10 minutes to build, the test times out. So we're going to get random failures if the machine is under load.

I think we could just build FLINT with --disable-static to reduce the probability of this happening.

**Pull request merged**
