### PR TITLE
add lerch_phi to fpwrap

### PR DESCRIPTION
**Pull request by vale981**
This is only a proposal. I haven't tested this.

### CODE REVIEW

**Comment by vale981** [comment]
done :). after the CI is through, i'll remove the accidental whitespace change

**Comment by vale981** [comment]
The tests work in the CI but I can't get it to compile locally.
Some outdated depency I think: ``bsplit_basecase_func_t`` is undeclared.

**Comment by fredrik-johansson** [comment]
> Some outdated dependency I think: bsplit_basecase_func_t is undeclared.

What version of flint are you building against? It should be present in the current git version (wbhart's repo) and the 2.9 beta.

**Comment by fredrik-johansson** [comment]
I forgot about docs: could you just add the functions to `doc/source/arb_fpwrap.rst` as well? Should be ready to merge after that!

**Comment by vale981** [comment]
done that :)

**Comment by fredrik-johansson** [comment]
> you're the most responsive repo-owner i've encountered so far

Thank you. 

(I'm not always responsive 😬 You were lucky to submit this on a good day...)

**Comment by vale981** [comment]
thank you for this nice project. it's hard to find a fast-ish lerch transcendent otherwise :)

**Pull request merged**
