### PR TITLE
MAINT: move upper incomplete gamma series from acb_poly to acb_hypgeom

### PR DESCRIPTION
**Pull request by argriffing**
part of https://github.com/fredrik-johansson/arb/issues/36

### CODE REVIEW

**Comment by argriffing** [comment]
fixed docs typo that had been present in the acb_poly docs (upper_gamma_series -> gamma-upper_series)

**Comment by fredrik-johansson** [comment]
The new version should have a regularized flag.

Later, there should also be a version of this function taking a series for the parameter. But that can wait.

**Comment by argriffing** [comment]
> The new version should have a regularized flag.

Added this.

**Comment by fredrik-johansson** [comment]
Thanks.

The regularized flag should go before n in the argument list.

In the regularized==1 branch, you can reuse t, u or v instead of creating c.

It's better to multiply by rgamma than dividing by gamma (consider s being a negative integer).

I'm confused by what happens in the regularized==2 branch. It seems to multiply by exp(-h(x)), which shouldn't give the right thing...

**Comment by argriffing** [comment]
> in the regularized==2 branch

Oops, it should be changed to z^-s instead of e^-z, right? I've made these changes.

**Comment by fredrik-johansson** [comment]
Aliasing seems to be broken now, because g is written to before the last time h is read from. Why does it pass the test code?

**Comment by argriffing** [comment]
> Why does it pass the test code?

The failure mode was nan+/-inf which passes the overlap test

**Comment by fredrik-johansson** [comment]
Okay, I think this should be fine now.

**Pull request merged**
