### PR TITLE
Add arf_fam function

### PR DESCRIPTION
**Pull request by rickyefarr**
This function is for fused addition and multiplication for the arf type.  This is part of a fix for issue #154

### CODE REVIEW

**Comment by rickyefarr** [comment]
Don't pull this in.  It appears as though I'll need to add the same variable that arf_addmul has so that this works as expected.

**Comment by rickyefarr** [comment]
For the time being, I will close this pull request and re-request when this issue is fixed fully.

**Comment by fredrik-johansson** [comment]
It would make sense to name it arf_fma and copy the MPFR operand order.

Also, it's probably not necessary to have separate implementations of fma and addmul since the code essentially is identical. addmul could just be changed to an inline function that invokes fma.

**Comment by rickyefarr** [comment]
Alright, I'll fix the code and update this.  The only part that may give me issues is the adaptation of the test module.

**Pull request closed without merging**
