### PR TITLE
return exact zero where possible: acos, acosh

### PR DESCRIPTION
**Pull request by rwst**
See #198

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
The code does not support aliasing properly, as res is written to before the last read of z.

**Comment by rwst** [comment]
Of course, I could simply clear and return after zeroing in acos(). Funny because I just did a clean up of such indentations in pynac...

**Comment by fredrik-johansson** [comment]
It's puzzling why t-acos and t-acosh don't fail since they are supposed to check aliasing.

**Comment by fredrik-johansson** [comment]
The variable one is not always being cleared (this technically doesn't matter since z=1 doesn't result in memory allocation, but it's not elegant).

**Comment by fredrik-johansson** [comment]
Aren't the functions mixed up? acosh should be real for x >= 1, acos should be real for -1 <= x <= 1. And acos is not actually equal to asin... it's a mystery that the test code isn't failing...

**Comment by rwst** [comment]
The results are not real, their real part should be exactly 0 (but isn't), as is proven for acosh in the link given in #198. I don't get your statement with asin, sorry.

**Comment by fredrik-johansson** [comment]
The logic you added to acb_acos does this:

if im(z) == 0 and re(z) >= 1, set res to re(asin(z))

The logic for acb_acosh checks if abs(re(z)) <= 1.

So the comparisons for acb_acos and acb_acosh seem to be switched, and additionally acb_acos is not giving the right value.

**Comment by rwst** [comment]
It is not about where acosh(z) is real, it's about where it is purely imaginary. This is the case with -1<z<1, but acb_acosh() returns a ball around 0.

I see for acos, that asin should have been negated.

**Comment by rwst** [comment]
I meant to say "...but acb_acosh() returns a ball around 0 as real part"

**Comment by fredrik-johansson** [comment]
OK thanks, I see. Though why use acb_sub when acb_neg is sufficient? :-)

**Comment by rwst** [comment]
I replaced with acb_neg . While testing passes on my machine Travis fails consistently in one place. Was Travis testing tested recently?

**Comment by fredrik-johansson** [comment]
It started timing out just now. Perhaps one of the Travis machines is under too heavy load or misconfigured. If it persists, we can lower the number of test iterations for that configuration.

**Comment by fredrik-johansson** [comment]
Thanks!

**Pull request merged**
